dataset_root: ./datasets_files/PHOENIX-2014-T/PHOENIX-2014-T
dict_path: ./datasets_files/PHOENIX-2014-T/info/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-T-groundtruth
